export type CaseComponent = 'miles' | 'rate' | 'grossRevenue' | 'earning' | 'reimbursement' | 'advances' | 'fuel' | 'toll' | 'recurring' | 'deductions' | 'escrow' | 'payout';
type ComponentResult = { fleetPilot: string | null; external: string | null; difference: string | null; source: string; exact: boolean; materialUnknown: boolean };
type CalculationSnapshot = { blockers: string[]; eligibleMilesThousandths: string; appliedRateMinorPerMile: string | null; percentageBaseMinor?: string | null; baseEarningMinor: string | null; calculatedPayoutMinor: string | null; components: Record<string, { amountMinor: string | null; availability: string }> };
type ExternalSnapshot = { milesThousandths: string | null; rateMinorPerMile: string | null; grossRevenueMinor?: string | null; earningMinor: string | null; reimbursementMinor: string | null; advancesMinor: string | null; fuelMinor: string | null; tollMinor: string | null; recurringMinor: string | null; deductionsMinor: string | null; escrowMinor: string | null; payoutMinor: string | null };
const difference = (left: string | null | undefined, right: string | null | undefined) => left == null || right == null ? null : (BigInt(left) - BigInt(right)).toString();
export function evaluatePayrollCase(calculation: CalculationSnapshot, external: ExternalSnapshot, sources: Record<string, string>) {
  const actual: Record<CaseComponent, string | null> = { miles: calculation.eligibleMilesThousandths, rate: calculation.appliedRateMinorPerMile, grossRevenue: calculation.percentageBaseMinor ?? null, earning: calculation.baseEarningMinor, reimbursement: calculation.components.reimbursements.amountMinor, advances: calculation.components.advances.amountMinor, fuel: calculation.components.fuel.amountMinor, toll: calculation.components.tolls.amountMinor, recurring: calculation.components.recurringDeductions.amountMinor, deductions: calculation.components.deductions.amountMinor, escrow: calculation.components.escrow.amountMinor, payout: calculation.calculatedPayoutMinor };
  const expected: Record<CaseComponent, string | null> = { miles: external.milesThousandths, rate: external.rateMinorPerMile, grossRevenue: external.grossRevenueMinor ?? null, earning: external.earningMinor, reimbursement: external.reimbursementMinor, advances: external.advancesMinor, fuel: external.fuelMinor, toll: external.tollMinor, recurring: external.recurringMinor, deductions: external.deductionsMinor, escrow: external.escrowMinor, payout: external.payoutMinor };
  const components = Object.fromEntries((Object.keys(actual) as CaseComponent[]).map((name) => {
    const source = sources[name] ?? 'UNAVAILABLE'; const externalValue = expected[name] ?? null; const knownZero = actual[name] === null && externalValue === '0' && source !== 'UNAVAILABLE'; const fleetPilot = knownZero ? '0' : actual[name]; const delta = difference(fleetPilot, externalValue); const materialUnknown = fleetPilot === null || externalValue === null || source === 'UNAVAILABLE';
    return [name, { fleetPilot, external: externalValue, difference: delta, source, exact: !materialUnknown && delta === '0', materialUnknown } satisfies ComponentResult];
  }));
  const materialComponents = (Object.keys(components) as CaseComponent[]).filter((name) => name !== 'grossRevenue' || actual.grossRevenue !== null || expected.grossRevenue !== null);
  const mismatches = materialComponents.filter((name) => !components[name].exact);
  const exactMatch = calculation.blockers.length === 0 && mismatches.length === 0;
  return { exactMatch, components, mismatches, blockers: calculation.blockers, accidentalNetMatch: components.payout.difference === '0' && !exactMatch };
}
