import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { prisma } from '@/lib/prisma';
import { AuthorizationService, type TrustedSession } from '@/lib/auth/authorization';
import { AuthorizationDeniedError } from '@/lib/auth/auth-errors';
import { PayrollPreviewService } from './payroll-preview-service';
import { PayrollVerificationService } from './payroll-verification-service';

const suffix = randomUUID().slice(0, 8); let session: TrustedSession = null; let companyId = ''; let foreignCompanyId = ''; let ownerId = ''; let memberId = ''; let driverId = ''; let foreignDriverId = ''; let periodId = '';
const auth = new AuthorizationService(prisma, async () => session); const preview = new PayrollPreviewService(prisma, auth); const service = new PayrollVerificationService(prisma, auth, preview); const use = (id: string) => { session = { user: { id } }; };
before(async () => {
  const [company, foreign] = await Promise.all([prisma.company.create({ data: { name: `Rules ${suffix}` } }), prisma.company.create({ data: { name: `Rules foreign ${suffix}` } })]); companyId = company.id; foreignCompanyId = foreign.id;
  const [owner, member] = await Promise.all([prisma.user.create({ data: { email: `rules-owner-${suffix}@test.dev`, displayName: 'Owner', activeCompanyId: companyId } }), prisma.user.create({ data: { email: `rules-member-${suffix}@test.dev`, displayName: 'Member', activeCompanyId: companyId } })]); ownerId = owner.id; memberId = member.id;
  await prisma.companyMembership.createMany({ data: [{ companyId, userId: ownerId, role: 'OWNER' }, { companyId, userId: memberId, role: 'MEMBER' }] });
  const [driver, foreignDriver] = await Promise.all([prisma.driver.create({ data: { companyId, firstName: 'Rule', lastName: 'Driver', payRate: .65 } }), prisma.driver.create({ data: { companyId: foreignCompanyId, firstName: 'Foreign', lastName: 'Driver', payRate: .65 } })]); driverId = driver.id; foreignDriverId = foreignDriver.id;
  use(ownerId); periodId = (await preview.createPeriod({ identifier: `RULE-${suffix}`, startDate: '2026-08-01', endDate: '2026-08-07' })).id;
});
after(async () => { await prisma.payrollReconciliationCase.deleteMany({ where: { companyId } }); await prisma.payrollRecurringDeductionRule.deleteMany({ where: { companyId } }); await prisma.payrollRule.deleteMany({ where: { companyId } }); await prisma.payrollPeriod.deleteMany({ where: { companyId } }); await prisma.driver.deleteMany({ where: { id: { in: [driverId, foreignDriverId] } } }); await prisma.companyMembership.deleteMany({ where: { userId: { in: [ownerId, memberId] } } }); await prisma.user.deleteMany({ where: { id: { in: [ownerId, memberId] } } }); await prisma.company.deleteMany({ where: { id: { in: [companyId, foreignCompanyId] } } }); await prisma.$disconnect(); });
test('OWNER stores evidence-based rules and readiness remains gated', async () => { use(ownerId); await service.saveRule({ type: 'MILEAGE_SOURCE', configuration: '{"policy":"LOAD_MILES","meaning":"unverified"}', verificationStatus: 'OBSERVED', tested: true }); const readiness = await service.readiness(); assert.equal(readiness.status, 'PARTIALLY_READY'); assert.equal(readiness.generationEnabled, false); assert.match(readiness.checks.find((item) => item.type === 'MILEAGE_SOURCE')!.blocker!, /verified/i); });
test('recurring deductions are preview rules and cross-company participants fail closed', async () => { use(ownerId); const rule = await service.createRecurringRule({ participantType: 'COMPANY_DRIVER', participantId: driverId, category: 'Insurance', description: 'Synthetic insurance', amount: '25.00', frequency: 'WEEKLY', effectiveFrom: '2026-08-01', verificationStatus: 'ADMIN_VERIFIED' }); assert.equal(rule.amountMinor, BigInt(2500)); await assert.rejects(service.createRecurringRule({ participantType: 'COMPANY_DRIVER', participantId: foreignDriverId, category: 'X', description: 'X', amount: '1', frequency: 'WEEKLY', effectiveFrom: '2026-08-01' }), /outside/i); });
test('audit case snapshots a blocked calculation without creating settlements or Accounting', async () => { use(ownerId); const beforeTransactions = await prisma.financialTransaction.count({ where: { companyId } }); const created = await service.createCase({ periodId, participantType: 'COMPANY_DRIVER', participantId: driverId, notes: 'Synthetic case' }); assert.equal(created.status, 'RULE_GAP'); assert.equal(await prisma.financialTransaction.count({ where: { companyId } }), beforeTransactions); assert.equal(await prisma.settlement.count({ where: { driverId } }), 0); });
test('MATCHED cannot be asserted over a blocked preview', async () => { use(ownerId); await assert.rejects(service.createCase({ periodId, participantType: 'COMPANY_DRIVER', participantId: driverId, status: 'MATCHED' }), /fully reconciled/i); });
test('MEMBER is denied and active-company tenant context is authoritative', async () => { use(memberId); await assert.rejects(service.listRules(), AuthorizationDeniedError); assert.equal(await prisma.payrollRule.count({ where: { companyId: foreignCompanyId } }), 0); });
