'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { formatMinorUnitsDecimal } from '@/lib/finance/money';

type Period = { id: string; identifier: string; startDate: string; endDate: string; status: string; externalPeriod?: string | null };
type Participant = { id: string; firstName?: string; lastName?: string; name?: string };
type Preview = { id: string; name: string; truck: { unitNumber: string } | null; calculation: { readiness: string; eligibleMilesThousandths: string; baseEarningMinor: string | null; calculatedPayoutMinor: string | null; payoutDifferenceMinor: string | null; blockers: string[]; warnings: string[]; tripBreakdown: Array<{ id: string; reference: string; miles: string | null; earningMinor: string | null }> } };
type PreviewResponse = { period: Period; previews: Preview[]; totals: Record<string, string | number>; contractorNotice: string };
const input = 'rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm';
const panel = 'rounded-xl border border-white/10 bg-slate-900/70 p-4';
const money = (minor: string | null) => minor === null ? 'Not available' : `$${formatMinorUnitsDecimal(BigInt(minor))}`;
const miles = (thousandths: string) => (Number(thousandths) / 1000).toLocaleString('en-US', { minimumFractionDigits: 3, maximumFractionDigits: 3 });
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'Request failed.'); return body as T; }

export default function PayrollPreviewWorkspace() {
  const [periods, setPeriods] = useState<Period[]>([]);
  const [drivers, setDrivers] = useState<Participant[]>([]);
  const [contractors, setContractors] = useState<Participant[]>([]);
  const [selectedPeriod, setSelectedPeriod] = useState('');
  const [preview, setPreview] = useState<PreviewResponse | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { const [nextPeriods, participants] = await Promise.all([api<Period[]>('/api/payroll/periods'), api<{ drivers: Participant[]; contractors: Participant[] }>('/api/payroll/participants')]); setPeriods(nextPeriods); setDrivers(participants.drivers); setContractors(participants.contractors); setSelectedPeriod((current) => current || nextPeriods[0]?.id || ''); }, []);
  useEffect(() => { refresh().catch((caught) => setError(caught.message)); }, [refresh]);
  useEffect(() => { if (!selectedPeriod) { setPreview(null); return; } api<PreviewResponse>(`/api/payroll/periods/${selectedPeriod}`).then(setPreview).catch((caught) => setError(caught.message)); }, [selectedPeriod]);
  async function submit(event: FormEvent<HTMLFormElement>, url: string) { event.preventDefault(); setBusy(true); setError(''); const form = event.currentTarget; try { await api(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); form.reset(); await refresh(); if (selectedPeriod) setPreview(await api(`/api/payroll/periods/${selectedPeriod}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Request failed.'); } finally { setBusy(false); } }
  const options = <><optgroup label="Company drivers">{drivers.map((driver) => <option key={driver.id} value={driver.id}>{driver.firstName} {driver.lastName}</option>)}</optgroup><optgroup label="Contractors">{contractors.map((contractor) => <option key={contractor.id} value={contractor.id}>{contractor.name}</option>)}</optgroup></>;
  return <main className="space-y-5 p-4 md:p-6">
    <header><p className="text-xs uppercase tracking-[.2em] text-amber-300">Payroll preview only</p><h1 className="text-2xl font-semibold">Payroll Audit &amp; Calculation Preview</h1><p className="text-sm text-slate-400">No payroll generation, settlement, payment, balance mutation, Accounting posting, or private QuickManage API access.</p></header>
    {error && <p role="alert" className="rounded-lg bg-red-950/60 p-3 text-red-200">{error}</p>}
    <section className={`${panel} grid gap-4 lg:grid-cols-3`}>
      <form onSubmit={(event) => submit(event, '/api/payroll/periods')} className="space-y-2"><h2 className="font-semibold">Create pay period</h2><input className={`${input} w-full`} name="identifier" placeholder="2026-W34" required /><div className="grid grid-cols-2 gap-2"><input aria-label="Start date" className={input} type="date" name="startDate" required /><input aria-label="End date" className={input} type="date" name="endDate" required /></div><input className={`${input} w-full`} name="externalPeriod" placeholder="Optional external period" /><input type="hidden" name="externalProvider" value="QUICKMANAGE" /><button disabled={busy} className="btn">Create preview period</button></form>
      <form onSubmit={(event) => submit(event, '/api/payroll/contracts')} className="space-y-2"><h2 className="font-semibold">Configure preview contract</h2><select className={`${input} w-full`} name="participantType"><option value="COMPANY_DRIVER">Company driver</option><option value="CONTRACTOR">Contractor</option></select><select className={`${input} w-full`} name="participantId" required>{options}</select><select className={`${input} w-full`} name="type"><option value="PER_MILE">Per mile</option><option value="PERCENTAGE">Percentage (blocked pending verified base)</option><option value="OTHER">Unsupported/other</option></select><input className={`${input} w-full`} name="ratePerMile" placeholder="Rate per mile, e.g. 0.65" /><input className={`${input} w-full`} name="percentage" placeholder="Percentage" /><select className={`${input} w-full`} name="percentageBase"><option value="UNKNOWN">Percentage base not configured</option><option value="GROSS_REVENUE">Gross revenue</option><option value="LINEHAUL">Linehaul</option><option value="TRIP_RATE">Trip rate</option></select><input aria-label="Contract effective date" className={`${input} w-full`} type="date" name="effectiveFrom" required /><button disabled={busy} className="btn">Save preview contract</button></form>
      <div className="space-y-3"><h2 className="font-semibold">Select pay period</h2><select aria-label="Pay period" className={`${input} w-full`} value={selectedPeriod} onChange={(event) => setSelectedPeriod(event.target.value)}><option value="">Select</option>{periods.map((period) => <option key={period.id} value={period.id}>{period.identifier}</option>)}</select><p className="text-xs text-amber-200">Current mileage policy: delivered loads in the period using <code>Load.miles</code>. This policy remains explicitly unverified for final payroll.</p></div>
    </section>
    {preview && <><section className={panel}><h2 className="font-semibold">Period summary</h2><div className="mt-2 flex flex-wrap gap-4 text-sm"><span>Participants: {preview.previews.length}</span><span>Blocked: {preview.totals.BLOCKED ?? 0}</span><span>Reconciled: {preview.totals.RECONCILED ?? 0}</span><span>Unreconciled: {preview.totals.UNRECONCILED ?? 0}</span><span>Calculated payout: {money(String(preview.totals.totalCalculatedPayoutMinor))}</span></div><p className="mt-2 text-xs text-amber-200">{preview.contractorNotice}</p></section><section className="grid gap-4 xl:grid-cols-2">{preview.previews.map((item) => <article key={item.id} className={panel}><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="text-xs text-slate-400">Truck {item.truck?.unitNumber ?? 'Not assigned'}</p></div><span className="h-fit rounded bg-slate-800 px-2 py-1 text-xs">{item.calculation.readiness}</span></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-slate-500">Eligible miles</dt><dd>{miles(item.calculation.eligibleMilesThousandths)}</dd></div><div><dt className="text-slate-500">Base earning</dt><dd>{money(item.calculation.baseEarningMinor)}</dd></div><div><dt className="text-slate-500">Calculated payout</dt><dd>{money(item.calculation.calculatedPayoutMinor)}</dd></div><div><dt className="text-slate-500">Reference difference</dt><dd>{money(item.calculation.payoutDifferenceMinor)}</dd></div></dl><details className="mt-3"><summary className="cursor-pointer text-sm">Calculation audit trail</summary><ul className="mt-2 space-y-1 text-xs">{item.calculation.tripBreakdown.map((trip) => <li key={trip.id}>{trip.reference}: {trip.miles ?? 'mileage unavailable'} miles → {money(trip.earningMinor)}</li>)}</ul></details>{item.calculation.blockers.length > 0 && <ul className="mt-3 list-disc pl-5 text-xs text-red-300">{item.calculation.blockers.map((warning) => <li key={warning}>{warning}</li>)}</ul>}{item.calculation.warnings.length > 0 && <ul className="mt-3 list-disc pl-5 text-xs text-amber-200">{item.calculation.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}</article>)}</section></>}
    {selectedPeriod && <section className={`${panel} grid gap-4 lg:grid-cols-2`}><form onSubmit={(event) => submit(event, '/api/payroll/adjustments')} className="space-y-2"><h2 className="font-semibold">Manual preview adjustment</h2><p className="text-xs text-amber-200">PAYROLL PREVIEW ONLY</p><input type="hidden" name="periodId" value={selectedPeriod} /><select className={`${input} w-full`} name="participantType"><option value="COMPANY_DRIVER">Company driver</option><option value="CONTRACTOR">Contractor</option></select><select className={`${input} w-full`} name="participantId" required>{options}</select><select className={`${input} w-full`} name="category">{['REIMBURSEMENT','CREDIT','ADVANCE','FUEL','TOLL','DEDUCTION','RECURRING_DEDUCTION','ESCROW','OTHER'].map((value) => <option key={value}>{value}</option>)}</select><input className={`${input} w-full`} name="amount" placeholder="Amount" required /><input className={`${input} w-full`} name="description" placeholder="Description" required /><input aria-label="Adjustment effective date" className={`${input} w-full`} type="date" name="effectiveDate" required /><input type="hidden" name="currency" value="USD" /><button disabled={busy} className="btn">Add preview adjustment</button></form><form onSubmit={(event) => submit(event, '/api/payroll/references')} className="space-y-2"><h2 className="font-semibold">External audit reference</h2><p className="text-xs text-slate-400">Comparison only; never posted to Accounting.</p><input type="hidden" name="periodId" value={selectedPeriod} /><input type="hidden" name="provider" value="QUICKMANAGE" /><select className={`${input} w-full`} name="participantType"><option value="COMPANY_DRIVER">Company driver</option><option value="CONTRACTOR">Contractor</option></select><select className={`${input} w-full`} name="participantId" required>{options}</select><input className={`${input} w-full`} name="externalStatementRef" placeholder="Statement reference" /><div className="grid grid-cols-2 gap-2">{['earning','reimbursement','fuel','toll','deductions','payout'].map((name) => <input key={name} className={input} name={name} placeholder={name} />)}</div><input type="hidden" name="currency" value="USD" /><button disabled={busy} className="btn">Save comparison reference</button></form></section>}
  </main>;
}
