import type { BankClassificationScope, FinancialDirection } from '@prisma/client';
import { NextResponse } from 'next/server';
import { financialControlAuthorization } from '@/lib/finance/financial-control-authorization';
import { bankLedgerRouteError } from '@/lib/finance/bank-ledger-route';
import { bankCategorizationService } from '@/lib/finance/bank-categorization';
import { BankLedgerValidationError } from '@/lib/finance/bank-ledger-errors';
import { PRIVATE_NO_STORE_HEADERS } from '@/lib/security/cache-headers';

type RouteContext = { params: Promise<{ id: string }> };
const optional = (value: unknown) => typeof value === 'string' && value.trim() ? value.trim() : null;
export async function PUT(request: Request, { params }: RouteContext) { try { const context = await financialControlAuthorization.requireContext('ADMIN'); const body = await request.json() as Record<string, unknown>; const categoryId = optional(body.categoryId); const scope = body.scope as BankClassificationScope; const direction = optional(body.direction) as FinancialDirection | null; if (!categoryId || !['COMPANY_LEVEL','ENTITY_ALLOCATED'].includes(scope)) throw new BankLedgerValidationError('Category and valid scope are required.'); if (direction && !['INFLOW','OUTFLOW','TRANSFER'].includes(direction)) throw new BankLedgerValidationError('Direction is invalid.'); let minimumAmountMinor: bigint | null; let maximumAmountMinor: bigint | null; try { minimumAmountMinor = body.minimumAmountMinor == null || body.minimumAmountMinor === '' ? null : BigInt(String(body.minimumAmountMinor)); maximumAmountMinor = body.maximumAmountMinor == null || body.maximumAmountMinor === '' ? null : BigInt(String(body.maximumAmountMinor)); } catch { throw new BankLedgerValidationError('Rule amount must be an integer number of minor units.'); } return NextResponse.json(await bankCategorizationService.updateRule(context, (await params).id, { name: String(body.name ?? ''), isEnabled: body.isEnabled !== false, merchantNormalized: optional(body.merchantNormalized), descriptionContains: optional(body.descriptionContains), direction, bankAccountId: optional(body.bankAccountId), minimumAmountMinor, maximumAmountMinor, categoryId, scope, truckId: optional(body.truckId), trailerId: optional(body.trailerId), driverId: optional(body.driverId), partyId: optional(body.partyId) }), { headers: PRIVATE_NO_STORE_HEADERS }); } catch (error) { return bankLedgerRouteError(error); } }
export async function PATCH(request: Request, { params }: RouteContext) { try { const context = await financialControlAuthorization.requireContext('ADMIN'); const body = await request.json() as Record<string, unknown>; return NextResponse.json(await bankCategorizationService.setRuleEnabled(context, (await params).id, body.isEnabled === true), { headers: PRIVATE_NO_STORE_HEADERS }); } catch (error) { return bankLedgerRouteError(error); } }
export async function DELETE(_: Request, { params }: RouteContext) { try { const context = await financialControlAuthorization.requireContext('ADMIN'); await bankCategorizationService.deleteRule(context, (await params).id); return new NextResponse(null, { status: 204, headers: PRIVATE_NO_STORE_HEADERS }); } catch (error) { return bankLedgerRouteError(error); } }
